replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env: []

ENABLE_FEATURE_X: "false"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  path: /ping
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /ping
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
