{{- range .Values.versions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ $.Release.Name }}
    version: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      version: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        version: {{ .name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
          env:
            - name: APP_VERSION
              value: {{ .name | quote }}
            - name: ENABLE_FEATURE_X
              value: {{ .enableFeatureX | quote }}
            {{- range $.Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.livenessProbe.path }}
              port: {{ $.Values.service.targetPort }}
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.readinessProbe.path }}
              port: {{ $.Values.service.targetPort }}
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
---
{{- end }}

