apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - mesh
    {{- if .Values.istio.gateway.enabled }}
    - {{ .Values.istio.gateway.name }}
    {{- end }}
  http:
    - name: feature-flag-to-v2
      match:
        - headers:
            {{ .Values.istio.featureFlag.routeHeader }}:
              exact: {{ .Values.istio.featureFlag.enabledValue | quote }}
      route:
        - destination:
            host: {{ .Values.istio.host }}
            subset: v2
          weight: 100
    - name: canary-v1-v2
      retries:
        attempts: {{ .Values.istio.retries.attempts }}
        perTryTimeout: {{ .Values.istio.retries.perTryTimeout }}
        retryOn: {{ .Values.istio.retries.retryOn | quote }}
      route:
        - destination:
            host: {{ .Values.istio.host }}
            subset: v1
          weight: {{ .Values.canary.v1Weight }}
        - destination:
            host: {{ .Values.istio.host }}
            subset: v2
          weight: {{ .Values.canary.v2Weight }}

